### ISSUE TITLE
Postar um exemplo de dados JSON. Data: 11/09.

### ISSUE THREAD

**Issue by tmsasaki** [troissant/ppads-projeto-05j-2018s2#5]

**Comment by troissant** [comment]
EXEMPLO FARMACIA JSON
  "drugstores": [
    {
      "id": "drogaraia",
      "name": "DrogaRaia",
      "category": "Farmácia",
      "deliveryEstimate": "25m",
      "rating": 4.9,
      "imagePath": "assets/img/farmacias/drogaraia.jpg",
      "about": "Droga Raia tem mais de 600 lojas espalhadas pelo Brasil e faz parte do grupo RD, com mais de 1.400 lojas.",
      "hours": "Funciona de segunda à sexta, de 8h às 23h"
    }
  ],

EXEMPLO COMPRA JSON
  "orders": [
    {
      "name": "Cleber Almeida",
      "email": "cleber109@gmail.com",
      "emailConfirmation": "cleber109@gmail.com",
      "address": "Rua Laranjeiras",
      "number": "650",
      "optionalAddress": "apto 21",
      "paymentOption": "DEB",
      "orderItems": [
        {
          "quantity": 1,
          "menuId": "cup-cake"
        }
      ],
      "id": 1
    }

Imagem do JSON abaixo:

![json](https://user-images.githubusercontent.com/22207303/45266136-98ce0780-b42c-11e8-84c0-2014cf1e2c75.png)
