### ISSUE TITLE
Selecionar um caso de uso para implementar na SPRINT 2. Escrever os fluxos alternativos deste caso de uso. Escrever um plano de testes (criar um arquivo plano-de-testes.md na pasta docs).

### ISSUE THREAD

**Issue by tmsasaki** [troissant/ppads-projeto-05j-2018s2#8]

**Comment by troissant** [comment]
Caso de uso escolhido: Acompanhar Pedido

**Comment by tmsasaki** [comment]
Escrever o plano de testes com procedimentos que o usuário deve realizar e o resultado esperado.

**Comment by tmsasaki** [comment]
Escrever um procedimento de teste para cada fluxo (seja principal ou alternativo) dos casos de uso.
